### ISSUE TITLE
When we click Ctrl+"Edit in Plunker" button, the Plunker is not opening in new tab.

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [angular/angularjs.org#149] opened 2015-01-05 16:49 UTC
When we click Ctrl+"Edit in Plunker" button, the plunker is not opening in new tab, instead it is opening the plunker in the same tab. But when we click Ctrl+edit in plunker button, it should open in the new tab, which is not happening as of now. And because of it we are unable to stay in the same page to refer the docs. When i click Ctrl+"Edit in Plunker" in "angular-ui.github.io/bootstrap/", the plunker is opening in a new tab. But this is not happenning in "angularjs.org". In "angularjs.org", when i do the same the plunker is opening in the same tab.

**Comment by jeffbcross** [comment] 2015-01-08 21:40
Closing as duplicate of angular/angular.js#10641

**Closed by jeffbcross** 2015-01-08 21:40 UTC
